# App-specific ProGuard rules only

# Keep line numbers for crash reports (optional)
-keepattributes SourceFile,LineNumberTable

# Add app-only rules here if needed

# ================= R8 AUTO-GENERATED MISSING RULES =================
# Generated by Android Gradle Plugin – safe to keep

-dontwarn com.app.videosdk.listener.PipListener
-dontwarn com.app.videosdk.model.PlayerModel
-dontwarn com.app.videosdk.ui.MtvVideoPlayerSdkKt

